version: '3.9'

services:
  dash:
    container_name: dash
    image: buldezir/traefik-app-dashboard:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dash.rule=Host(`${TRAEFIK_RULE_HOST}`)"
      - "traefik.http.routers.dash.entrypoints=websecure"
      # - "traefik.http.routers.dash.tls.certresolver=letsencrypt"
      - "traefik.http.services.dash.loadbalancer.server.port=80"

networks:
  traefik:
    external: true